# file này để khởi chạy các dịch vụ phụ trợ
# Cần lệnh docker-compose up -d -> tạo container cho Postgres + MinIO, cấu hình đúng port, user/pass, volume dể backend kết nối ngay và dùng
# Các image này được lấy từ Docker hub chính thức
services:

  db:
    # dùng image sẵn trên Docker Hub
    image: postgres:17
    restart: always
    # tạo user, password, database mặc định
    environment:
      POSTGRES_USER: postgredb
      POSTGRES_PASSWORD: postgredb
      POSTGRES_DB: face-recognition
    # mở port 5432 ra ngoài để có thể connect từ máy host
    ports:
      - '5435:5432'
    #  gắn một thư mục (volume) để lưu dữ liệu ra ngoài container -> khi container xóa thì dữ liệu vẫn còn
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

  # khi có nhiều service trong cùng một docker-compose.yml, chúng nằm chung trong một mạng nội bộ cho Docker quản lý

  # tóm lại file này dùng để tạo môi trường các thứ cho postgres, minio
  # việc còn lại là phải tự tạo cấu trúc như table, dữ liệu ...
